#!/bin/bash

if [ ! -d "$1" ]; then
  echo "Директории '$1' не существует!"
  exit 1
fi

find "$1" -type f -name "*.bak" -delete
find "$1" -type f -name "*.tmp" -delete
find "$1" -type f -name "*.backup" -delete

echo "Очистка директории '$1' завершена."
